### ISSUE TITLE
怎么设置显示上个月的以及下个月的部分日期

### ISSUE THREAD

**Issue by GTooo** [huangyanbin/CalendarView#1]
如题，看了下代码，没找到在哪里设置，求解

**Comment by huangyanbin** [comment]
点击跳转上一个月：monthViewPager.setCurrentItem(monthViewPager.getCurrentItem() - 1);
  点击跳转下一个月：monthViewPager.setCurrentItem(monthViewPager.getCurrentItem() + 1);
**# 您好，在OnCalenderListener的public RecordState setSignDateStatus(CustomDate date)，通过回调需要显示日期，你只需要将当前日期的状态返回就可以，如果你觉得显示的类型不够多，可以在RecordStats增加。
CalendarActivity 中实现了这个接口，你可以参考一下。****

**Comment by 532922397** [comment]
第三张效果图实现方法，求解
